blank_issues_enabled: false
contact_links:
  - name: TestFlight Beta
    url: https://testflight.apple.com/join/4AncqeX3
    about: Join the public beta to test new features before App Store release.
